version: "3"
services:
  springboot-app:
    #container_name: spring-app
    image: lscudeler/projeto_department_user:1.0
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  db:
    container_name: mysqldb
    image: mysql:8
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root

volumes:
  dbbase: